
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "conveyor"
readme = "README.md"
dependencies = ["torch", "flashinfer", "outlines", "vllm", "transformers"]

[tool.pytest]
testpaths = ["test"]